name: Expo Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout repo
        uses: actions/checkout@v3

      - name: 🟩 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📥 Install dependencies
        run: npm ci

      - name: 🔐 Authenticate with Expo
        run: npx expo login --token ${{ secrets.EXPO_TOKEN }}

      - name: 🚀 Publish to Expo
        run: npx expo publish
